# Generated by Django 5.0 on 2023-12-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScores',
            fields=[
                ('roll_no', models.CharField(db_column='ROLL_NO', max_length=10, primary_key=True, serialize=False)),
                ('hackerrank', models.TextField(blank=True, db_column='HackerRank', null=True)),
                ('hackerrank_score', models.IntegerField(db_column='HackerRank_Score')),
                ('codeforces', models.TextField(blank=True, db_column='CodeForces', null=True)),
                ('codeforces_score', models.IntegerField(db_column='CodeForces_Score')),
                ('codechef', models.TextField(blank=True, db_column='CodeChef', null=True)),
                ('codechef_score', models.IntegerField(db_column='CodeChef_Score')),
                ('spoj', models.TextField(blank=True, db_column='Spoj', null=True)),
                ('spoj_score', models.IntegerField(db_column='Spoj_Score')),
                ('interviewbit', models.TextField(blank=True, db_column='InterviewBit', null=True)),
                ('interviewbit_score', models.IntegerField(db_column='InterviewBit_Score')),
                ('leetcode', models.TextField(blank=True, db_column='LeetCode', null=True)),
                ('leetcode_score', models.IntegerField(db_column='LeetCode_Score')),
                ('gfg', models.TextField(blank=True, db_column='GFG', null=True)),
                ('gfg_score', models.IntegerField(db_column='GFG_Score')),
                ('overall_score', models.IntegerField(db_column='Overall_score')),
                ('daily_scores', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='R21',
            fields=[
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('roll_number', models.CharField(db_column='Roll_Number', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb3_general_ci', db_column='Name', max_length=39)),
                ('branch', models.CharField(db_collation='utf8mb3_general_ci', db_column='Branch', max_length=7)),
                ('username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Username', max_length=16, null=True)),
                ('last_login', models.DateField(blank=True, db_column='LAST_LOGIN', null=True)),
                ('mobile', models.BigIntegerField(db_column='Mobile')),
                ('email', models.CharField(db_collation='utf8mb3_general_ci', db_column='Email', max_length=45)),
                ('hackerrank_username', models.CharField(blank=True, db_column='HackerRank_UserName', max_length=20, null=True)),
                ('algorithms_hackerrank_field', models.CharField(db_column='Algorithms', max_length=16)),
                ('codechef_username', models.CharField(db_column='CodeChef_UserName', max_length=19)),
                ('cc_problems_solved', models.IntegerField(db_column='CC_Problems_Solved')),
                ('ccps_10', models.IntegerField(db_column='CCPS_10', default=0)),
                ('codeforces_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Codeforces_UserName', max_length=24)),
                ('cf_problems_solved', models.IntegerField(db_column='CF_Problems_Solved')),
                ('cfps_10', models.IntegerField(db_column='CFPS_10', default=0)),
                ('spoj_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Spoj_UserName', max_length=19)),
                ('spoj_problems_solved', models.IntegerField(db_column='Spoj_Problems_Solved')),
                ('sps_20', models.IntegerField(db_column='SPS_20', default=0)),
                ('overall_score', models.IntegerField(db_column='Overall_Score')),
            ],
            options={
                'db_table': 'r21',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='R22',
            fields=[
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Name', max_length=31, null=True)),
                ('email', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Email', max_length=54, null=True)),
                ('roll_number', models.CharField(db_column='Roll_Number', max_length=11, primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(db_collation='utf8mb3_general_ci', db_column='Mobile_No', max_length=11)),
                ('branch', models.CharField(db_collation='utf8mb3_general_ci', db_column='Branch', max_length=7)),
                ('hackerrank_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='HackerRank_UserName', max_length=26)),
                ('algorithms', models.IntegerField(blank=True, db_column='Algorithms', null=True)),
                ('codeforces_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Codeforces_UserName', max_length=24)),
                ('cf_problems_solved', models.IntegerField(blank=True, db_column='CF_Problems_Solved', null=True)),
                ('cfps_10', models.IntegerField(blank=True, db_column='CFPS_10', null=True)),
                ('codechef_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='CodeChef_UserName', max_length=19)),
                ('cc_problems_solved', models.IntegerField(blank=True, db_column='CC_Problems_Solved', null=True)),
                ('ccps_10', models.IntegerField(blank=True, db_column='CCPS_10', null=True)),
                ('spoj_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Spoj_UserName', max_length=18)),
                ('spoj_problems_solved', models.IntegerField(blank=True, db_column='Spoj_Problems_Solved', null=True)),
                ('sps_20', models.IntegerField(blank=True, db_column='SPS_20', null=True)),
                ('interviewbit_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='InterviewBit_Username', max_length=37)),
                ('ib_problems_solved', models.IntegerField(blank=True, db_column='IB_Problems_Solved', null=True)),
                ('ib_10', models.IntegerField(blank=True, db_column='IB_10', null=True)),
                ('leetcode_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='LeetCode_Username', max_length=23)),
                ('leet_problems_solved', models.IntegerField(blank=True, db_column='Leet_Problems_Solved', null=True)),
                ('lp_10', models.IntegerField(blank=True, db_column='LP_10', null=True)),
                ('geeksforgeeks_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='GeeksForGeeks_Username', max_length=24)),
                ('gfg_problems_solved', models.IntegerField(blank=True, db_column='GFG_Problems_Solved', null=True)),
                ('gfg_10', models.IntegerField(blank=True, db_column='GFG_10', null=True)),
                ('overall_score', models.IntegerField(db_column='Overall_Score')),
            ],
            options={
                'db_table': 'r22',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('rank', models.IntegerField(blank=True, db_column='RANK', null=True)),
                ('roll_no', models.OneToOneField(db_column='ROLL_NO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.studentscores')),
                ('name', models.CharField(db_column='NAME', max_length=39)),
                ('course', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Course', max_length=7, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('branch', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Branch', max_length=3, null=True)),
                ('sec', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Sec', max_length=1, null=True)),
                ('hackerrank_username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='HackerRank_Username', max_length=48, null=True)),
                ('codeforces_username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='CodeForces_Username', max_length=40, null=True)),
                ('codechef_username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='CodeChef_Username', max_length=92, null=True)),
                ('spoj_username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Spoj_Username', max_length=22, null=True)),
                ('interviewbit_username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='InterviewBit_Username', max_length=42, null=True)),
                ('leetcode_username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='LeetCode_Username', max_length=29, null=True)),
                ('gfg_username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='GFG_Username', max_length=48, null=True)),
            ],
            options={
                'db_table': 'student_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackerrank_username', models.CharField(max_length=50)),
                ('codeforces_username', models.CharField(max_length=50)),
                ('codechef_username', models.CharField(max_length=50)),
                ('spoj_username', models.CharField(max_length=50)),
                ('interviewbit_username', models.CharField(max_length=50)),
                ('leetcode_username', models.CharField(max_length=50)),
                ('gfg_username', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentmaster')),
            ],
        ),
    ]
