# Generated by Django 4.2.6 on 2023-10-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r21',
            name='total_ccps_10_field',
            field=models.CharField(db_collation='utf8mb3_general_ci', db_column='Total(CCPS*10)', max_length=14),
        ),
        migrations.AlterField(
            model_name='r21',
            name='total_cfps_10_field',
            field=models.CharField(db_collation='utf8mb3_general_ci', db_column='Total(CFPS*10)', max_length=14),
        ),
        migrations.AlterField(
            model_name='r21',
            name='total_sps_20_field',
            field=models.CharField(db_collation='utf8mb3_general_ci', db_column='Total(SPS*20)', max_length=13),
        ),
    ]
