# Generated by Django 5.0 on 2024-01-02 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(max_length=200)),
                ('date_input', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='R21',
            fields=[
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('roll_number', models.CharField(db_column='Roll_Number', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb3_general_ci', db_column='Name', max_length=39)),
                ('branch', models.CharField(db_collation='utf8mb3_general_ci', db_column='Branch', max_length=7)),
                ('username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Username', max_length=16, null=True)),
                ('last_login', models.DateField(blank=True, db_column='LAST_LOGIN', null=True)),
                ('mobile', models.BigIntegerField(db_column='Mobile')),
                ('email', models.CharField(db_collation='utf8mb3_general_ci', db_column='Email', max_length=45)),
                ('hackerrank_username', models.CharField(blank=True, db_column='HackerRank_UserName', max_length=20, null=True)),
                ('algorithms_hackerrank_field', models.CharField(db_column='Algorithms', max_length=16)),
                ('codechef_username', models.CharField(db_column='CodeChef_UserName', max_length=19)),
                ('cc_problems_solved', models.IntegerField(db_column='CC_Problems_Solved')),
                ('ccps_10', models.IntegerField(db_column='CCPS_10', default=0)),
                ('codeforces_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Codeforces_UserName', max_length=24)),
                ('cf_problems_solved', models.IntegerField(db_column='CF_Problems_Solved')),
                ('cfps_10', models.IntegerField(db_column='CFPS_10', default=0)),
                ('spoj_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Spoj_UserName', max_length=19)),
                ('spoj_problems_solved', models.IntegerField(db_column='Spoj_Problems_Solved')),
                ('sps_20', models.IntegerField(db_column='SPS_20', default=0)),
                ('overall_score', models.IntegerField(db_column='Overall_Score')),
            ],
            options={
                'db_table': 'r21',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='R22',
            fields=[
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Name', max_length=31, null=True)),
                ('email', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Email', max_length=54, null=True)),
                ('roll_number', models.CharField(db_column='Roll_Number', max_length=11, primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(db_collation='utf8mb3_general_ci', db_column='Mobile_No', max_length=11)),
                ('branch', models.CharField(db_collation='utf8mb3_general_ci', db_column='Branch', max_length=7)),
                ('hackerrank_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='HackerRank_UserName', max_length=26)),
                ('algorithms', models.IntegerField(blank=True, db_column='Algorithms', null=True)),
                ('codeforces_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Codeforces_UserName', max_length=24)),
                ('cf_problems_solved', models.IntegerField(blank=True, db_column='CF_Problems_Solved', null=True)),
                ('cfps_10', models.IntegerField(blank=True, db_column='CFPS_10', null=True)),
                ('codechef_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='CodeChef_UserName', max_length=19)),
                ('cc_problems_solved', models.IntegerField(blank=True, db_column='CC_Problems_Solved', null=True)),
                ('ccps_10', models.IntegerField(blank=True, db_column='CCPS_10', null=True)),
                ('spoj_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Spoj_UserName', max_length=18)),
                ('spoj_problems_solved', models.IntegerField(blank=True, db_column='Spoj_Problems_Solved', null=True)),
                ('sps_20', models.IntegerField(blank=True, db_column='SPS_20', null=True)),
                ('interviewbit_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='InterviewBit_Username', max_length=37)),
                ('ib_problems_solved', models.IntegerField(blank=True, db_column='IB_Problems_Solved', null=True)),
                ('ib_10', models.IntegerField(blank=True, db_column='IB_10', null=True)),
                ('leetcode_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='LeetCode_Username', max_length=23)),
                ('leet_problems_solved', models.IntegerField(blank=True, db_column='Leet_Problems_Solved', null=True)),
                ('lp_10', models.IntegerField(blank=True, db_column='LP_10', null=True)),
                ('geeksforgeeks_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='GeeksForGeeks_Username', max_length=24)),
                ('gfg_problems_solved', models.IntegerField(blank=True, db_column='GFG_Problems_Solved', null=True)),
                ('gfg_10', models.IntegerField(blank=True, db_column='GFG_10', null=True)),
                ('overall_score', models.IntegerField(db_column='Overall_Score')),
            ],
            options={
                'db_table': 'r22',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackerrank_username', models.CharField(max_length=50)),
                ('codeforces_username', models.CharField(max_length=50)),
                ('codechef_username', models.CharField(max_length=50)),
                ('spoj_username', models.CharField(max_length=50)),
                ('interviewbit_username', models.CharField(max_length=50)),
                ('leetcode_username', models.CharField(max_length=50)),
                ('gfg_username', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentmaster')),
            ],
        ),
    ]
