# Generated by Django 4.2.6 on 2023-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_r21_total_ccps_10_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='R22',
            fields=[
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Name', max_length=31, null=True)),
                ('email', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Email', max_length=54, null=True)),
                ('roll_no', models.CharField(db_column='Roll_No', max_length=11, primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(db_collation='utf8mb3_general_ci', db_column='Mobile_No', max_length=11)),
                ('branch', models.CharField(db_collation='utf8mb3_general_ci', db_column='Branch', max_length=7)),
                ('hackerrank_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='HackerRank_UserName', max_length=26)),
                ('algorithms', models.IntegerField(blank=True, db_column='Algorithms', null=True)),
                ('codeforces_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Codeforces_UserName', max_length=24)),
                ('cf_problems_solved', models.IntegerField(blank=True, db_column='CF_Problems_Solved', null=True)),
                ('cfps_20', models.IntegerField(blank=True, db_column='CFPS_20', null=True)),
                ('codechef_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='CodeChef_UserName', max_length=19)),
                ('cc_problems_solved', models.IntegerField(blank=True, db_column='CC_Problems_Solved', null=True)),
                ('ccps_10', models.IntegerField(blank=True, db_column='CCPS_10', null=True)),
                ('spoj_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Spoj_UserName', max_length=18)),
                ('spoj_problems_solved', models.IntegerField(blank=True, db_column='Spoj_Problems_Solved', null=True)),
                ('sps_20', models.IntegerField(blank=True, db_column='SPS_20', null=True)),
                ('interviewbit_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='InterviewBit_Username', max_length=37)),
                ('ib_problems_solved', models.IntegerField(blank=True, db_column='IB_Problems_Solved', null=True)),
                ('ib_10', models.IntegerField(blank=True, db_column='IB_10', null=True)),
                ('leetcode_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='LeetCode_Username', max_length=23)),
                ('leet_problems_solved', models.IntegerField(blank=True, db_column='Leet_Problems_Solved', null=True)),
                ('lp_10', models.IntegerField(blank=True, db_column='LP_10', null=True)),
                ('geeksforgeeks_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='GeeksForGeeks_Username', max_length=24)),
                ('gfg_problems_solved', models.IntegerField(blank=True, db_column='GFG_Problems_Solved', null=True)),
                ('gfg_10', models.IntegerField(blank=True, db_column='GFG_10', null=True)),
                ('overall_score', models.IntegerField(db_column='Overall_Score')),
            ],
            options={
                'db_table': 'r22',
                'managed': True,
            },
        ),
    ]
