# Generated by Django 4.2.8 on 2024-01-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_anouncement_alter_studentscores_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anouncement',
            new_name='Announcement',
        ),
        migrations.AlterModelTable(
            name='studentscores',
            table='student_scores',
        ),
    ]
