# Generated by Django 4.2.6 on 2023-10-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_r21_total_ccps_10_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r21',
            name='total_ccps_10_field',
            field=models.CharField(db_collation='utf8mb3_general_ci', db_column='CCPS_10', max_length=14),
        ),
        migrations.AlterField(
            model_name='r21',
            name='total_cfps_10_field',
            field=models.CharField(db_collation='utf8mb3_general_ci', db_column='CFPS_10', max_length=14),
        ),
        migrations.AlterField(
            model_name='r21',
            name='total_sps_20_field',
            field=models.CharField(db_collation='utf8mb3_general_ci', db_column='SPS_20', max_length=13),
        ),
    ]
