# Generated by Django 4.2.6 on 2023-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_r21_total_ccps_10_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r21',
            name='total_ccps_10_field',
        ),
        migrations.RemoveField(
            model_name='r21',
            name='total_cfps_10_field',
        ),
        migrations.RemoveField(
            model_name='r21',
            name='total_sps_20_field',
        ),
        migrations.AddField(
            model_name='r21',
            name='ccps_10',
            field=models.IntegerField(db_column='CCPS_10', default=0),
        ),
        migrations.AddField(
            model_name='r21',
            name='cfps_10',
            field=models.IntegerField(db_column='CFPS_10', default=0),
        ),
        migrations.AddField(
            model_name='r21',
            name='sps_20',
            field=models.IntegerField(db_column='SPS_20', default=0),
        ),
        migrations.AlterField(
            model_name='r21',
            name='algorithms_hackerrank_field',
            field=models.CharField(db_column='Algorithms', max_length=16),
        ),
        migrations.AlterField(
            model_name='r21',
            name='cc_problems_solved',
            field=models.IntegerField(db_column='CC_Problems_Solved'),
        ),
        migrations.AlterField(
            model_name='r21',
            name='cf_problems_solved',
            field=models.IntegerField(db_column='CF_Problems_Solved'),
        ),
        migrations.AlterField(
            model_name='r21',
            name='codechef_username',
            field=models.CharField(db_column='CodeChef_UserName', max_length=19),
        ),
        migrations.AlterField(
            model_name='r21',
            name='spoj_problems_solved',
            field=models.IntegerField(db_column='Spoj_Problems_Solved'),
        ),
    ]
